### ISSUE TITLE
[heejay-reservation-cancel-modal] 예약현황 화면에서 예약취소 선택 시 confirm 모달 구현

### ISSUE THREAD

**Issue by heejaykong** [SukheeChoi/springframework-mini-project#186]
구현해야하는 자잘한 기능 발견해서 작성합니다. 이걸 개발할 사람은 누가 될까요

#### AS-IS
~예약현황 화면에서 예약취소 선택 시 취소사유 입력하는 과정 없이 바로 바로 취소하고 그냥 window.reload()함~
-> 수정: 예약현황 화면에서 예약취소 선택 시 confirm 모달이 뜨는 과정 없이 바로 취소하고 window.reload()함 
#### TO-BE
~예약현황 화면에서 예약취소 선택 시 취소사유 입력하는 모달기능 구현하기~
-> 수정: 예약현황 화면에서 예약취소 선택 시 "정말 취소하시겠습니까?" 물어보는 confirm 모달기능 구현하기 && 디폴트로 취소사유는 "본인 취소"로 DB에 들어가게 하기

**Comment by SukheeChoi** [comment]
예약 취소 사유는 사용자가 아닌 병원이 입력하는 거라서 취소 후에 바로 리로드 했어요~

**Comment by heejaykong** [comment]
-> 팀장님과 이야기한 결과 사용자가 취소한 경우에는 취소사유를 입력하는게 아닌, "정말 취소하시겠습니까" 물어보는 confirm모달 기능만 구현하고 DB에 취소사유 값으론 디폴트로 "본인 취소"라고 넣기로 했음 ㅎㅎ (만약 병원이 예약을 취소해서 취소사유를 병원이 입력했다고 가정하려면 추후에 dentist 서버단에서 더미데이터로 넣어야 함)
